language: node_js
node_js:
  - 14

stages:
  - name: script
    if: branch = main

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./public
  on:
    branch: main
